---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: asa-py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asa-py-app
  template:
    metadata:
      labels:
        app: asa-py-app
    spec:
      containers:
        - name: aap
          image: asa-py-devfile:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: asa-py-app
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: asa-py-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app
  labels:
    app: asa-py-app
spec:
  to:
    kind: Service
    name: asa-py-app
    weight: 100
  port:
    targetPort: 8081
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
